{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-clustcurv
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/clustcurv_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/clustcurv/clustcurv_{{ version }}.tar.gz
  sha256: 64e968b294eaa8064e0d2ccd5ba43de52bd4b8f546c71dc9e10dea336a4fb0de

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-gmedian
    - r-rcolorbrewer
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-ggfortify
    - r-ggplot2
    - r-npregfast
    - r-survival
  run:
    - r-base
    - r-gmedian
    - r-rcolorbrewer
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-ggfortify
    - r-ggplot2
    - r-npregfast
    - r-survival

test:
  commands:
    - $R -e "library('clustcurv')"           # [not win]
    - "\"%R%\" -e \"library('clustcurv')\""  # [win]

about:
  home: https://github.com/noramvillanueva/clustcurv
  license: MIT
  summary: 'A method for determining groups in multiple curves with an automatic selection of their number based on k-means or k-medians algorithms. The selection of the optimal number is provided by bootstrap methods. The methodology can be applied both in regression and survival framework. Implemented methods are: Grouping
    multiple survival curves described by Villanueva et al. (2018) <doi:10.1002/sim.8016>.'
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
